import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";
import SinglePost from "../../../components/Post/SinglePost";
import { getAllPosts, getAllPostsForToppage } from "../../../lib/notionAPI";
// import Pagination from "../../../components/Pagination/Pagination";
// import Tag from "../../../components/Tag/Tag";

export const getStaticPaths: GetStaticPaths = async () => {

  return {
    paths: [{ params: {page: "1"} }, { params: {page: "2"} }],
    fallback: "blocking",
  };
};

export const getStaticProps: GetStaticProps = async () => {
  const fourPosts = await getAllPostsForToppage(4);

  return {
    props: {
      fourPosts,
    },
    revalidate: 60 * 60 * 24,
  };
};

const BlogPageList = ({ fourPosts }) => {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">
          Notion Blog🚀
        </h1>
        {fourPosts.map((post) => (
          <div className="mx-4">
            <SinglePost
              title={post.title}
              description={post.description}
              date={post.date}
              tags={post.tags}
              slug={post.slug}
            />
          </div>
        ))}
      </main>
    </div>
  );
};

export default BlogPageList;
