import { GetStaticProps } from "next";
import Head from "next/head";
// import Link from "next/link";
// import SinglePost from "../components/Post/SinglePost";
// import Tag from "../components/Tag/Tag";
// import { getAllTags, getPostsForTopPage } from "../lib/notionAPI";

// export const getStaticProps: GetStaticProps = async () => {
//   const fourPosts = await getPostsForTopPage(4);
//   const allTags = await getAllTags();

//   return {
//     props: {
//       fourPosts,
//       allTags,
//     },
//     revalidate: 10,
//   };
// };

export default function Home() {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">
          Notion Blog🚀
        </h1>
      </main>
    </div>
  );
}
